/**
 * The deck — cards, books, levels, and what has been recited.
 *
 * Pure bookkeeping over data/game/deck.json (generated by
 * tools/build-deck.mjs): which cards a level reveals, which the player has
 * recited and how often, how much XP that has earned, and which card the
 * stage should offer next. No rendering, no meters — game.js owns those.
 */

let LEVELS = [], BOOKS = [], CARDS = [];
let byId = new Map();

/** recited: cardId → times recited. The save file's heart. */
let recited = new Map();

/* ── The player's own books ("upload Atomic Habits") ────────────────────── */
//
// A modern book is the player's to bring: pasted text or a .txt, split into
// readable pages, each page a recitable card on its own shelf. Stored only
// in this browser (localStorage) — the game reads what the player gives it
// and claims nothing about the rights to it.

const USER_KEY = 'recite-game-books-v1';
let userBooks = []; // [{ id, title, pages: [{ title, recite, text }] }]

function loadUserBooks() {
  try { userBooks = JSON.parse(localStorage.getItem(USER_KEY) ?? '[]'); }
  catch { userBooks = []; }
}
function saveUserBooks() {
  try { localStorage.setItem(USER_KEY, JSON.stringify(userBooks)); } catch {}
}

/** Split raw text into pages a person could actually read aloud. */
export function paginate(text, target = 650) {
  const paras = text.replace(/\r\n/g, '\n').split(/\n\s*\n|\n/).map((p) => p.trim()).filter(Boolean);
  const pages = [];
  let cur = '';
  for (const p of paras) {
    if (cur && cur.length + p.length > target) { pages.push(cur); cur = p; }
    else cur = cur ? cur + '\n\n' + p : p;
    // a single huge paragraph still has to break somewhere
    while (cur.length > target * 1.6) {
      const cut = cur.lastIndexOf('. ', target);
      const at = cut > target * 0.4 ? cut + 1 : target;
      pages.push(cur.slice(0, at).trim());
      cur = cur.slice(at).trim();
    }
  }
  if (cur) pages.push(cur);
  return pages;
}

function userBookEntries() {
  const books = [], cards = [];
  for (const b of userBooks) {
    books.push({ id: b.id, title: b.title, icon: '📕', user: true });
    b.pages.forEach((p, i) => {
      cards.push({
        id: `${b.id}.P${i + 1}`, book: b.id, category: 'Modern', level: 1,
        title: `${p.title ?? `Page ${i + 1}`}`, sub: b.title,
        recite: p.recite, text: p.text,
      });
    });
  }
  return { books, cards };
}

let baseBooks = [], baseCards = [];

function rebuild() {
  const u = userBookEntries();
  BOOKS = [...baseBooks, ...u.books];
  CARDS = [...baseCards, ...u.cards];
  byId = new Map(CARDS.map((c) => [c.id, c]));
}

export function addUserBook(title, text) {
  const pages = paginate(text).map((t) => ({
    title: null,
    recite: t.split(/(?<=[.!?])\s/)[0].slice(0, 180),
    text: t,
  }));
  if (!pages.length) return null;
  const id = `USR.${Date.now().toString(36)}`;
  userBooks.push({ id, title: title.trim() || 'An untitled book', pages });
  saveUserBooks();
  rebuild();
  return id;
}

export function removeUserBook(id) {
  const b = userBooks.find((x) => x.id === id);
  if (!b) return;
  userBooks = userBooks.filter((x) => x !== b);
  for (const cid of [...recited.keys()]) if (cid.startsWith(id + '.')) recited.delete(cid);
  saveUserBooks();
  rebuild();
}

export function initDeck(deckData, savedRecited) {
  LEVELS = deckData.levels;
  baseBooks = deckData.books;
  baseCards = deckData.cards;
  loadUserBooks();
  rebuild();
  recited = new Map(savedRecited ?? []);
  // A save from an older deck may hold ids the deck no longer ships. Drop
  // them rather than crash — the XP they earned is honestly gone with them.
  for (const id of [...recited.keys()]) if (!byId.has(id)) recited.delete(id);
}

export const allCards = () => CARDS;
export const allBooks = () => BOOKS;
export const levelTable = () => LEVELS;
export const card = (id) => byId.get(id);
export const recitedEntries = () => [...recited.entries()];
export const recitedCount = () => recited.size;
export const timesRecited = (id) => recited.get(id) ?? 0;

/** XP: a first recital is worth a card; a re-recital keeps it warm. */
const XP_FIRST = 10;
const XP_AGAIN = 2;

export function totalXP() {
  let xp = 0;
  for (const n of recited.values()) xp += XP_FIRST + (n - 1) * XP_AGAIN;
  return xp;
}

export function levelFor(xp) {
  let lv = 1;
  for (const L of LEVELS) if (xp >= L.xp) lv = L.lv;
  return lv;
}

export const levelName = (lv) =>
  LEVELS.find((L) => L.lv === lv)?.name ?? `Level ${lv}`;

/** XP still needed for the next level, or null at the top. */
export function nextLevelAt(lv) {
  return LEVELS.find((L) => L.lv === lv + 1)?.xp ?? null;
}

export const unlockedCards = (lv) => CARDS.filter((c) => c.level <= lv);
export const cardsAtLevel = (lv) => CARDS.filter((c) => c.level === lv);

/** Record one recital. Returns { first, xpGained }. */
export function recordRecital(id) {
  const n = (recited.get(id) ?? 0) + 1;
  recited.set(id, n);
  return { first: n === 1, xpGained: n === 1 ? XP_FIRST : XP_AGAIN };
}

/**
 * What the stage offers next: the first revealed card never yet recited
 * (deck order is level order, so the arc reads correctly), else the
 * longest-unrefreshed one — old teachings are always worth re-reading.
 */
export function nextCard(lv) {
  const open = unlockedCards(lv);
  const fresh = open.find((c) => !recited.has(c.id));
  if (fresh) return fresh;
  return open[0] ?? null;
}

/** Per-book progress for the doors and the Books page. */
export function bookProgress() {
  return BOOKS.map((b) => {
    const all = CARDS.filter((c) => c.book === b.id);
    const done = all.filter((c) => recited.has(c.id)).length;
    return { ...b, total: all.length, done };
  });
}
