/**
 * The deck — cards, books, levels, and what has been recited.
 *
 * Pure bookkeeping over data/game/deck.json (generated by
 * tools/build-deck.mjs): which cards a level reveals, which the player has
 * recited and how often, how much XP that has earned, and which card the
 * stage should offer next. No rendering, no meters — game.js owns those.
 */

let LEVELS = [], BOOKS = [], CARDS = [];
let byId = new Map();

/** recited: cardId → times recited. The save file's heart. */
let recited = new Map();

export function initDeck(deckData, savedRecited) {
  LEVELS = deckData.levels;
  BOOKS = deckData.books;
  CARDS = deckData.cards;
  byId = new Map(CARDS.map((c) => [c.id, c]));
  recited = new Map(savedRecited ?? []);
  // A save from an older deck may hold ids the deck no longer ships. Drop
  // them rather than crash — the XP they earned is honestly gone with them.
  for (const id of [...recited.keys()]) if (!byId.has(id)) recited.delete(id);
}

export const allCards = () => CARDS;
export const allBooks = () => BOOKS;
export const levelTable = () => LEVELS;
export const card = (id) => byId.get(id);
export const recitedEntries = () => [...recited.entries()];
export const recitedCount = () => recited.size;
export const timesRecited = (id) => recited.get(id) ?? 0;

/** XP: a first recital is worth a card; a re-recital keeps it warm. */
const XP_FIRST = 10;
const XP_AGAIN = 2;

export function totalXP() {
  let xp = 0;
  for (const n of recited.values()) xp += XP_FIRST + (n - 1) * XP_AGAIN;
  return xp;
}

export function levelFor(xp) {
  let lv = 1;
  for (const L of LEVELS) if (xp >= L.xp) lv = L.lv;
  return lv;
}

export const levelName = (lv) =>
  LEVELS.find((L) => L.lv === lv)?.name ?? `Level ${lv}`;

/** XP still needed for the next level, or null at the top. */
export function nextLevelAt(lv) {
  return LEVELS.find((L) => L.lv === lv + 1)?.xp ?? null;
}

export const unlockedCards = (lv) => CARDS.filter((c) => c.level <= lv);
export const cardsAtLevel = (lv) => CARDS.filter((c) => c.level === lv);

/** Record one recital. Returns { first, xpGained }. */
export function recordRecital(id) {
  const n = (recited.get(id) ?? 0) + 1;
  recited.set(id, n);
  return { first: n === 1, xpGained: n === 1 ? XP_FIRST : XP_AGAIN };
}

/**
 * What the stage offers next: the first revealed card never yet recited
 * (deck order is level order, so the arc reads correctly), else the
 * longest-unrefreshed one — old teachings are always worth re-reading.
 */
export function nextCard(lv) {
  const open = unlockedCards(lv);
  const fresh = open.find((c) => !recited.has(c.id));
  if (fresh) return fresh;
  return open[0] ?? null;
}

/** Per-book progress for the doors and the Books page. */
export function bookProgress() {
  return BOOKS.map((b) => {
    const all = CARDS.filter((c) => c.book === b.id);
    const done = all.filter((c) => recited.has(c.id)).length;
    return { ...b, total: all.length, done };
  });
}
