# -*- coding: utf-8 -*-
"""Seed corpus, part 2. See seed/README.md for the provenance caveat."""

JHARKHAND = [
 (1765,None,"exact","legislature","The Chotanagpur plateau passes to the Company",
  "With the Diwani of Bengal, the forested plateau and its Munda, Ho and Santhal communities came under Company revenue administration — a system built for settled wet-rice agriculture applied to shifting, clan-held forest land.",
  ["annexation","revenue_extraction","revenue_settlement"],0.7,0.85,["East India Company"],["Chotanagpur"],[]),
 (1831,1832,"exact","war","The Kol uprising",
  "Munda and Ho cultivators rose against outsider landholders and moneylenders installed under Company revenue arrangements. Suppression was severe; the grievance — alienation of tribal land — did not go away.",
  ["rebellion","displacement","agitation"],0.8,0.82,["Munda community","Ho community"],["Chotanagpur"],[]),
 (1855,1856,"exact","war","The Santhal Hool",
  "Sidhu and Kanhu Murmu led tens of thousands of Santhals against zamindars, moneylenders and the Company. It was crushed with heavy loss of life, but forced the creation of a separately administered Santhal Parganas.",
  ["rebellion","displacement","agitation"],0.9,0.88,["Sidhu Murmu","Kanhu Murmu"],["Santhal Parganas"],[]),
 (1899,1900,"exact","war","Birsa Munda's Ulgulan",
  "Birsa Munda led an armed movement to restore the khuntkatti collective land system against dikus and the colonial state. Birsa died in custody at 25; the rebellion directly shaped the tenancy law that followed.",
  ["rebellion","displacement","agitation"],0.9,0.9,["Birsa Munda"],["Khunti","Ranchi"],[]),
 (1908,None,"exact","legislature","The Chotanagpur Tenancy Act",
  "Enacted in the wake of the Ulgulan, the CNT Act restricted transfer of tribal land to non-tribals. It remains the central instrument — and the central political battleground — of land rights in the region.",
  ["land_reform"],0.9,0.9,["Government of Bengal"],["Chotanagpur"],[]),
 (1907,1912,"exact","development","Tata Steel is built at Sakchi",
  "Jamsetji Tata's plan for an integrated steelworks was sited where iron ore, coal and water met. Sakchi became Jamshedpur — a company town, and the beginning of the plateau's role as a resource hinterland.",
  ["mineral_discovery","industrial_boom","urbanisation","displacement"],0.95,0.92,["Jamsetji Tata","Dorabji Tata"],["Jamshedpur","Sakchi"],[]),
 (1948,1960,"decade","development","The Damodar Valley Corporation dams",
  "Modelled on the Tennessee Valley Authority, the DVC built dams for flood control and power. They generated electricity for industry elsewhere and displaced tens of thousands of largely Adivasi families locally.",
  ["dam_built","electrification","displacement"],0.85,0.85,["Damodar Valley Corporation"],["Damodar Valley"],[]),
 (1955,1965,"decade","development","Bokaro, Ranchi and the public sector build-out",
  "Bokaro Steel, Heavy Engineering Corporation at Ranchi and the coalfields made the region the core of India's industrial base — under central ownership, with profits, management and skilled jobs largely flowing outward.",
  ["industrial_boom","mineral_discovery","displacement","urbanisation"],0.85,0.85,["Government of India"],["Bokaro","Ranchi","Dhanbad"],[]),
 (1973,None,"exact","movement","The Jharkhand Mukti Morcha is founded",
  "The JMM fused Adivasi land grievance with coalfield labour organising, giving the statehood demand — voiced since the 1930s Adivasi Mahasabha — a mass vehicle.",
  ["statehood_demand","agitation","caste_mobilisation"],0.85,0.88,["Shibu Soren","A. K. Roy","Binod Bihari Mahato"],["Dhanbad"],[]),
 (2000,None,"exact","legislature","Jharkhand attains statehood",
  "Carved out of southern Bihar on 15 November 2000 — Birsa Munda's birth anniversary — after seven decades of agitation. The new state held immense mineral wealth and among India's worst human development indicators.",
  ["state_reorganisation","statehood_demand"],0.95,0.96,[],["Jharkhand"],[]),
 (2000,2015,"decade","war","Maoist insurgency in the mineral belt",
  "Left-wing extremism entrenched across the forested districts, drawing on displacement, land alienation and absent state services. The insurgency concentrated precisely where extraction was densest.",
  ["insurgency","rebellion","displacement"],0.85,0.82,[],["Saranda","Palamu","West Singhbhum"],["contested_history"]),
 (2005,2020,"decade","development","MoUs, mining leases and the resource paradox",
  "Successive governments signed large mining and steel MoUs. Royalty accrued to the state while land acquisition, resettlement failures and litigation left many projects stalled and communities displaced.",
  ["displacement","industrial_boom","revenue_surge","agitation"],0.8,0.78,[],["Jharkhand"],[]),
]

TAMIL_NADU = [
 (-300,300,"century","craft","The Sangam age and the Chera-Chola-Pandya trade",
  "Sangam poetry and excavations at Keezhadi and Arikamedu attest to literate urban settlement, Roman trade and specialised craft — bead-making, shell, iron and fine textiles — across the Tamil country.",
  ["craft_flourish","port_established"],0.75,0.7,["Chera","Chola","Pandya"],["Keezhadi","Arikamedu","Madurai"],["contested_history"]),
 (850,None,"decade","highlight","Vijayalaya founds the imperial Chola line",
  "The capture of Thanjavur began the Chola resurgence that would build the most powerful maritime state in Indian history and one of its most sophisticated revenue and temple administrations.",
  ["dynastic_patronage"],0.8,0.85,["Vijayalaya Chola"],["Thanjavur"],[]),
 (1010,None,"exact","craft","The Brihadeeswarar temple is completed",
  "Rajaraja I's granite temple at Thanjavur, with its 60-metre vimana, was funded by war booty and endowed with land, dancers, musicians and craftsmen. Its inscriptions are a complete audit of an economy.",
  ["temple_construction","dynastic_patronage","craft_flourish","guild_formation"],0.9,0.95,["Rajaraja Chola I"],["Thanjavur"],[]),
 (1025,None,"exact","war","Rajendra Chola's naval expedition to Srivijaya",
  "A Chola fleet raided Srivijayan ports across the Malacca Strait, securing the eastern trade route. It is the only sustained overseas naval projection by a pre-modern Indian state.",
  ["battle","invasion","port_boom"],0.85,0.85,["Rajendra Chola I"],["Srivijaya","Nagapattinam"],[]),
 (1639,None,"exact","development","Fort St George founded at Madras",
  "The Company acquired a coastal strip from the Nayak of Wandiwash and built Fort St George; the weaving villages around it grew into Madras, the Company's first city and its southern base.",
  ["port_established","urbanisation","craft_flourish"],0.85,0.9,["Francis Day","East India Company"],["Madras"],[]),
 (1801,None,"exact","legislature","The Carnatic is annexed and Madras Presidency consolidated",
  "The Nawab's territories passed to the Company and the ryotwari settlement was extended, assessing individual cultivators directly rather than through zamindars — a different extraction machine from Bengal's.",
  ["annexation","revenue_settlement","revenue_extraction"],0.8,0.88,["East India Company","Thomas Munro"],["Madras Presidency"],[]),
 (1876,1878,"exact","disaster","The Great Famine of Madras",
  "Drought met a policy of non-interference with grain markets and export continued through the crisis. Mortality across the Madras Presidency ran into millions; relief was rationed on a deliberately punitive scale.",
  ["famine","drought","crop_failure","population_loss","migration"],0.95,0.9,["Lord Lytton","Richard Temple"],["Madras Presidency"],[]),
 (1916,None,"exact","movement","The South Indian Liberal Federation is founded",
  "The Justice Party organised non-Brahmin professional and landed interests, and in office introduced communal representation in education and public employment — the origin of reservation policy in India.",
  ["caste_mobilisation","agitation"],0.85,0.88,["Justice Party","T. M. Nair","P. Theagaraya Chetty"],["Madras"],[]),
 (1925,None,"exact","movement","Periyar launches the Self-Respect Movement",
  "The movement attacked caste, priestly authority and the subordination of women, and built an institutional and rhetorical base that would dominate Tamil politics for the next century.",
  ["caste_mobilisation","agitation"],0.9,0.9,["Periyar E. V. Ramasamy"],["Erode","Madras"],[]),
 (1937,1965,"decade","movement","The anti-Hindi agitations",
  "Compulsory Hindi in schools in 1937, and the 1965 transition to Hindi as sole official language, both met mass agitation and deaths. The outcome was the indefinite continuation of English alongside Hindi.",
  ["language_movement","agitation"],0.95,0.92,["Periyar E. V. Ramasamy","C. N. Annadurai"],["Madras State"],[]),
 (1967,None,"exact","highlight","The DMK takes power",
  "Annadurai's DMK ended Congress rule; no national party has governed Tamil Nadu since. Dravidian parties made welfare provision the currency of electoral competition.",
  ["agitation","caste_mobilisation"],0.9,0.95,["C. N. Annadurai","DMK"],["Tamil Nadu"],[]),
 (1969,None,"exact","legislature","Madras State is renamed Tamil Nadu",
  "The renaming formalised the linguistic-cultural identity that the Dravidian movement had built, four years after the anti-Hindi agitation of 1965.",
  ["state_reorganisation","language_movement"],0.7,0.95,["C. N. Annadurai"],["Tamil Nadu"],[]),
 (1982,None,"exact","development","The midday meal scheme is universalised",
  "M. G. Ramachandran extended the noon meal to all primary schoolchildren. Enrolment and retention rose sharply; the scheme was later adopted nationally on the Tamil Nadu template.",
  ["literacy_drive","public_health_drive","literacy_rise"],0.9,0.9,["M. G. Ramachandran"],["Tamil Nadu"],[]),
 (1995,2015,"decade","development","Chennai becomes an automotive and IT hub",
  "Ford, Hyundai and a deep supplier base made Chennai India's largest car-exporting cluster, while Tidel Park and the IT corridor built a software economy on the state's long-standing engineering-education capacity.",
  ["industrial_boom","it_boom","policy_liberalisation","urbanisation"],0.85,0.85,[],["Chennai","Sriperumbudur"],[]),
 (2004,None,"exact","disaster","The Indian Ocean tsunami",
  "The tsunami killed thousands along the Coromandel coast and destroyed the boats and gear of fishing communities. Reconstruction reshaped coastal settlement and fisheries policy.",
  ["earthquake","flood","population_loss","displacement"],0.85,0.95,[],["Nagapattinam","Cuddalore"],[]),
 (2015,None,"exact","disaster","The Chennai floods",
  "Record rainfall met a city built over its own drainage — the Pallikaranai marsh and the Adyar and Cooum floodplains. Urbanisation, not only rainfall, set the scale of the disaster.",
  ["flood","urbanisation"],0.8,0.92,[],["Chennai"],[]),
]

PUNJAB = [
 (1469,None,"exact","culture","Guru Nanak is born at Talwandi",
  "Nanak's teaching rejected caste, ritual and religious boundary, and established the institutions — sangat, langar, the line of Gurus — from which a distinct Punjabi social order grew.",
  ["dynastic_patronage"],0.9,0.95,["Guru Nanak"],["Nankana Sahib"],[]),
 (1577,1604,"exact","development","Amritsar is founded and the Adi Granth installed",
  "Guru Ram Das founded the town and Guru Arjan compiled and installed the Adi Granth in the Harmandir Sahib, giving the community a centre, a scripture and a market town in one.",
  ["urbanisation","dynastic_patronage"],0.8,0.9,["Guru Ram Das","Guru Arjan"],["Amritsar"],[]),
 (1699,None,"exact","movement","The Khalsa is founded at Anandpur",
  "Guru Gobind Singh instituted the Khalsa, transforming a devotional community into a self-defending one. It set the organisational form that would carry Punjab through the eighteenth century.",
  ["caste_mobilisation"],0.9,0.93,["Guru Gobind Singh"],["Anandpur Sahib"],[]),
 (1799,1839,"exact","highlight","Ranjit Singh builds the Sikh Empire",
  "Ranjit Singh took Lahore in 1799 and forged the misls into a state stretching from the Sutlej to the Khyber — secular in appointment, formidable in arms, and the last major Indian power to fall to the British.",
  ["annexation","dynastic_patronage"],0.95,0.93,["Maharaja Ranjit Singh"],["Lahore"],[]),
 (1849,None,"exact","war","Annexation after the Second Anglo-Sikh War",
  "Following Chillianwala and Gujrat, the Company annexed the Punjab. It became the Raj's principal recruiting ground and, later, the target of its largest irrigation investment.",
  ["annexation","battle"],0.9,0.93,["Lord Dalhousie","Duleep Singh"],["Punjab"],[]),
 (1885,1920,"decade","development","The canal colonies",
  "The Chenab, Jhelum and Lower Bari Doab canals irrigated millions of acres of western Punjab waste, settled by peasant grantees. It was the largest agricultural colonisation scheme of the colonial era.",
  ["canal_built","irrigation_expansion","migration","agri_yield_rise","urbanisation"],0.95,0.9,["Punjab Government"],["Lyallpur","Chenab Colony"],[]),
 (1907,None,"exact","movement","The Colonization Bill agitation",
  "Terms imposed on canal-colony grantees provoked the 'Pagri Sambhal Jatta' agitation led by Ajit Singh and Kishan Singh; the Bill was withdrawn. Punjab's tradition of organised agrarian protest starts here.",
  ["agitation","caste_mobilisation"],0.75,0.85,["Ajit Singh","Banke Dayal"],["Lyallpur"],[]),
 (1919,None,"exact","war","The Jallianwala Bagh massacre",
  "Troops under Dyer fired on an enclosed gathering in Amritsar, killing hundreds. It ended moderate faith in constitutional reform and made non-cooperation a mass proposition.",
  ["rebellion","population_loss"],0.95,0.97,["Reginald Dyer","Michael O'Dwyer"],["Amritsar"],[]),
 (1947,None,"exact","war","Partition",
  "Punjab was cut in two. Around ten million people crossed the new border and hundreds of thousands died; East Punjab lost its canal colonies, its western cities and a third of its irrigated land.",
  ["partition","migration","population_loss"],1.0,0.97,[],["Punjab"],[]),
 (1966,None,"exact","legislature","The Punjabi Suba and reorganisation",
  "After sustained agitation, Punjab was reorganised on linguistic lines into Punjab, Haryana and hill districts transferred to Himachal, with Chandigarh a shared capital — an arrangement still unresolved.",
  ["state_reorganisation","language_movement","statehood_demand"],0.9,0.93,["Sant Fateh Singh","Akali Dal"],["Punjab","Chandigarh"],[]),
 (1966,1980,"decade","development","The Green Revolution",
  "High-yielding wheat and rice, tubewells, assured procurement and subsidised power tripled output. Punjab fed the national buffer stock and became India's richest state per capita within a decade.",
  ["agri_yield_rise","irrigation_expansion","electrification","policy_liberalisation"],1.0,0.95,["M. S. Swaminathan","Punjab Agricultural University"],["Ludhiana","Punjab"],[]),
 (1978,1995,"decade","war","Militancy and the decade of violence",
  "Demands framed in the Anandpur Sahib Resolution, Centre-state disputes over river waters and Chandigarh, and armed separatism produced a sustained insurgency and heavy state counter-action.",
  ["insurgency","rebellion","population_loss"],0.95,0.85,[],["Punjab"],["contested_history","sensitive"]),
 (1984,None,"exact","war","Operation Blue Star and its aftermath",
  "The army operation in the Harmandir Sahib complex, the assassination of the Prime Minister and the anti-Sikh massacres that followed in Delhi and elsewhere marked the year that made reconciliation hardest.",
  ["insurgency","rebellion","population_loss","migration"],1.0,0.9,[],["Amritsar","Delhi"],["contested_history","sensitive"]),
 (1985,None,"exact","legislature","The Rajiv-Longowal Accord",
  "The accord promised Chandigarh to Punjab and a tribunal on river waters. Longowal was assassinated weeks later and the core terms were never implemented, leaving the grievances live.",
  ["peace_accord"],0.8,0.9,["Rajiv Gandhi","Harchand Singh Longowal"],["Punjab"],[]),
 (1995,2020,"decade","disaster","Groundwater depletion and the paddy trap",
  "Free power and assured paddy procurement drove tubewell irrigation far past recharge; water tables fell metres per decade across central Punjab. The Green Revolution's incentive structure became its own constraint.",
  ["irrigation_expansion","drought","agri_yield_fall"],0.9,0.85,[],["Punjab"],[]),
 (2020,2021,"exact","movement","The farm laws protest",
  "Punjab farmers led a year-long encampment against three farm laws seen as threatening assured procurement. The laws were repealed — the clearest recent instance of Punjab's agrarian organising capacity.",
  ["agitation","policy_liberalisation"],0.9,0.93,["Samyukt Kisan Morcha"],["Punjab","Delhi borders"],[]),
]
