# -*- coding: utf-8 -*-
"""Seed corpus, part 1. See seed/README.md for the provenance caveat."""

KERALA = [
 (-50,300,"century","development","Muziris and the Roman spice trade",
  "The Malabar port of Muziris anchored a maritime pepper trade reaching Rome; Roman gold coin hoards and the Periplus attest to sustained exchange. Spice wealth, not agriculture, set the coast's early economic pattern.",
  ["port_established","craft_flourish","revenue_surge"],0.7,0.72,["Chera dynasty","Roman merchants"],["Muziris","Malabar Coast"],[]),
 (1341,None,"exact","disaster","The Periyar flood silts Muziris and opens Kochi",
  "A catastrophic Periyar flood silted the Muziris harbour and scoured open a new natural harbour at Kochi. Trade primacy shifted down the coast within a generation — geography, not policy, redrew Kerala's economy.",
  ["flood","port_established","revenue_decline"],0.85,0.78,[],["Periyar River","Kochi","Muziris"],[]),
 (1498,None,"exact","highlight","Vasco da Gama lands at Kappad",
  "Da Gama reached Kappad near Kozhikode, opening the direct Europe–India sea route. The Zamorin's court received him; within two decades the pepper trade was being contested by armed European fleets rather than negotiated.",
  ["trade_treaty"],0.9,0.95,["Vasco da Gama","Zamorin of Calicut"],["Kappad","Kozhikode"],[]),
 (1503,None,"exact","war","Portuguese fort at Kochi",
  "The Portuguese built Fort Manuel at Kochi, their first fortified base in India, backing the Kochi raja against the Zamorin. Armed European presence became permanent on the Malabar coast.",
  ["annexation","port_established"],0.65,0.9,["Afonso de Albuquerque"],["Kochi"],[]),
 (1663,None,"exact","war","The Dutch take Kochi from the Portuguese",
  "The Dutch East India Company captured Kochi, ending Portuguese primacy in Malabar and reorganising the pepper monopoly around Dutch factories.",
  ["annexation","battle"],0.6,0.9,["Dutch East India Company"],["Kochi"],[]),
 (1741,None,"exact","war","Battle of Colachel",
  "Travancore under Marthanda Varma defeated a Dutch East India Company force at Colachel — a rare Asian land victory over a European naval power. It ended Dutch ambitions in Malabar and freed Travancore to consolidate.",
  ["battle"],0.8,0.9,["Marthanda Varma","Eustachius De Lannoy"],["Colachel"],[]),
 (1750,None,"exact","legislature","Trippadidanam: Travancore dedicated to Padmanabha",
  "Marthanda Varma formally surrendered the kingdom to the deity Padmanabha and ruled as its regent. The act fused sovereignty with temple authority and gave the state unusual legitimacy for centralising reform.",
  ["dynastic_patronage"],0.6,0.85,["Marthanda Varma"],["Thiruvananthapuram"],[]),
 (1795,None,"exact","legislature","Travancore becomes a British subsidiary ally",
  "Travancore entered subsidiary alliance with the East India Company, retaining internal autonomy while ceding defence and paying a subsidy. Princely autonomy is what later allowed Travancore's distinctive social spending.",
  ["annexation","revenue_extraction"],0.6,0.85,["East India Company"],["Travancore"],[]),
 (1817,None,"exact","legislature","Travancore's royal rescript on education",
  "Rani Gowri Parvati Bai ordered that the state defray the cost of education so that 'there should be no backwardness in the spread of enlightenment'. It is among the earliest state commitments to mass schooling anywhere in India.",
  ["literacy_drive"],0.85,0.8,["Rani Gowri Parvati Bai"],["Travancore"],[]),
 (1859,None,"exact","movement","The Channar revolt concludes",
  "After decades of agitation, Nadar women won the right to cover their upper bodies. The struggle established public protest over caste dignity as a durable Kerala political form.",
  ["caste_mobilisation","agitation"],0.7,0.78,["Nadar community"],["South Travancore"],[]),
 (1924,1925,"exact","movement","Vaikom Satyagraha",
  "A twenty-month satyagraha won the right to use roads around the Vaikom temple regardless of caste. It drew Gandhi and Periyar, and set the template for Kerala's temple-entry campaigns.",
  ["caste_mobilisation","agitation"],0.85,0.88,["T. K. Madhavan","Periyar E. V. Ramasamy","Mahatma Gandhi"],["Vaikom"],[]),
 (1936,None,"exact","legislature","Temple Entry Proclamation",
  "Chithira Thirunal Balarama Varma opened Travancore's state temples to all Hindus regardless of caste — a legislative act of social reform decades ahead of comparable measures elsewhere.",
  ["caste_mobilisation"],0.85,0.9,["Chithira Thirunal Balarama Varma"],["Travancore"],[]),
 (1949,None,"exact","legislature","Travancore and Cochin merge",
  "The two princely states merged into Travancore-Cochin, the administrative step that made a united Malayalam-speaking state possible seven years later.",
  ["state_reorganisation"],0.6,0.9,[],["Travancore","Cochin"],[]),
 (1956,None,"exact","legislature","Kerala formed under the States Reorganisation Act",
  "Travancore-Cochin merged with the Malabar district of Madras State to form Kerala on 1 November 1956, uniting Malayalam speakers under one administration for the first time.",
  ["state_reorganisation","language_movement"],0.95,0.97,[],["Kerala"],[]),
 (1957,None,"exact","highlight","The world's first elected communist government takes office",
  "E. M. S. Namboodiripad's ministry took power through the ballot — among the earliest communist governments anywhere to be freely elected. It moved immediately on land and education.",
  ["land_reform","literacy_drive"],0.95,0.95,["E. M. S. Namboodiripad","Communist Party of India"],["Kerala"],[]),
 (1957,None,"exact","legislature","The Kerala Education Bill",
  "The bill brought private (largely church- and caste-managed) schools under state regulation of pay and appointments. It vastly widened access and triggered the backlash that toppled the government.",
  ["literacy_drive"],0.8,0.88,["Joseph Mundassery"],["Kerala"],[]),
 (1959,None,"exact","movement","The Liberation Struggle and President's Rule",
  "A coalition of church, Nair Service Society and Congress interests mounted the Vimochana Samaram; the elected government was dismissed under Article 356 — an early and much-cited use of central power against a state ministry.",
  ["agitation","caste_mobilisation"],0.8,0.88,["Nair Service Society","Catholic Church","Indian National Congress"],["Kerala"],["contested_history"]),
 (1969,1970,"exact","legislature","Kerala Land Reforms (Amendment) Act",
  "The Act abolished tenancy, conferred ownership on cultivating tenants and granted hutment-dwellers title to their homesteads. Implementation from 1970 broke landlordism more thoroughly than in any other Indian state.",
  ["land_reform","displacement"],0.95,0.93,["C. Achutha Menon","K. R. Gouri Amma"],["Kerala"],[]),
 (1973,1990,"decade","development","The Gulf migration and the remittance economy",
  "After the 1973 oil boom, Malayali labour migration to the Gulf became mass-scale. Remittances rather than industry funded housing, education and consumption, producing high human development without a manufacturing base.",
  ["migration","remittance_inflow","urbanisation"],0.9,0.85,[],["Persian Gulf","Kerala"],[]),
 (1991,None,"exact","development","Kerala declared fully literate",
  "The total literacy campaign, run through mass volunteer mobilisation, led to Kerala's declaration as India's first fully literate state — the compounding payoff of state schooling begun in 1817 and widened in 1957.",
  ["literacy_rise","literacy_drive"],0.9,0.9,["Kerala Shastra Sahitya Parishad"],["Kerala"],[]),
 (1996,None,"exact","legislature","The People's Plan Campaign",
  "Kerala devolved around a third of its plan budget to local governments with participatory planning. It is the most substantial decentralisation experiment attempted by an Indian state.",
  ["cooperative_formation"],0.75,0.85,["Kerala State Planning Board"],["Kerala"],[]),
 (2018,None,"exact","disaster","The Kerala floods",
  "The worst flooding since 1924 displaced over a million people. Recovery leaned heavily on local government capacity and diaspora remittance — the institutions built over the preceding decades.",
  ["flood","migration"],0.85,0.95,[],["Kerala"],[]),
]

WEST_BENGAL = [
 (1204,None,"decade","war","Bakhtiyar Khalji takes Nadia",
  "Ikhtiyar al-Din Muhammad Bakhtiyar Khalji's raid on Nadia broke Sena power in western Bengal and opened five centuries of Islamic rule in the delta.",
  ["invasion","annexation"],0.8,0.82,["Bakhtiyar Khalji","Lakshmana Sena"],["Nadia"],[]),
 (1352,None,"decade","highlight","Ilyas Shah unifies the Bengal Sultanate",
  "Shamsuddin Ilyas Shah consolidated Lakhnauti, Satgaon and Sonargaon into an independent Bengal Sultanate, beginning a period of distinct Bengali courtly culture and Persian–Bengali literary patronage.",
  ["dynastic_patronage"],0.75,0.85,["Shamsuddin Ilyas Shah"],["Lakhnauti","Sonargaon"],[]),
 (1576,None,"exact","war","Battle of Rajmahal and Mughal annexation",
  "Akbar's forces defeated Daud Khan Karrani, making Bengal a Mughal subah. Bengal became the empire's richest revenue province — and therefore its most extracted one.",
  ["battle","annexation","revenue_extraction"],0.8,0.88,["Akbar","Daud Khan Karrani"],["Rajmahal"],[]),
 (1690,None,"exact","development","Calcutta founded as a Company factory",
  "Job Charnock settled at Sutanuti; the villages of Sutanuti, Kalikata and Govindapur grew into Calcutta. A riverine trading post became, within a century, the capital of British India.",
  ["port_established","urbanisation"],0.85,0.85,["Job Charnock","East India Company"],["Calcutta"],[]),
 (1757,None,"exact","war","Battle of Plassey",
  "Robert Clive defeated Siraj-ud-Daulah at Palashi, largely through the defection of Mir Jafar. The Company gained the power to install a Nawab — the hinge on which British territorial rule in India turns.",
  ["battle","annexation"],1.0,0.98,["Robert Clive","Siraj-ud-Daulah","Mir Jafar"],["Palashi"],[]),
 (1765,None,"exact","legislature","The Company obtains the Diwani of Bengal",
  "After Buxar, the Company received the right to collect revenue in Bengal, Bihar and Orissa. It became a tax-gathering state while remaining nominally a trading company — the structural cause of the extraction that followed.",
  ["revenue_extraction","revenue_settlement"],0.95,0.95,["East India Company","Shah Alam II"],["Bengal"],[]),
 (1770,None,"exact","disaster","The Great Bengal Famine",
  "Harvest failure compounded by undiminished revenue demand killed an estimated ten million — perhaps a third of the population. Revenue collection in 1770-71 was maintained at or above prior levels.",
  ["famine","crop_failure","population_loss","revenue_extraction"],1.0,0.93,["East India Company"],["Bengal"],[]),
 (1793,None,"exact","legislature","The Permanent Settlement",
  "Cornwallis fixed land revenue in perpetuity with zamindars as proprietors. It guaranteed Company income, created a rentier landlord class, and left cultivators without security — a settlement whose effects outlast the Raj.",
  ["revenue_settlement","revenue_extraction"],0.95,0.96,["Lord Cornwallis"],["Bengal"],[]),
 (1800,1870,"decade","craft","The collapse of Bengal's handloom weaving",
  "Company monopsony, punitive duties on Indian cloth in Britain, and then machine-spun Lancashire imports destroyed a weaving economy that had clothed much of the world. Muslin and Baluchari traditions nearly vanished.",
  ["craft_collapse","deindustrialisation","migration"],0.9,0.8,["East India Company"],["Murshidabad","Santipur","Dhaka"],[]),
 (1854,None,"exact","development","The first railway line out of Howrah",
  "The East Indian Railway opened Howrah–Hooghly, beginning the network that would move coal, jute and troops — and pull the rural interior into a port-facing economy.",
  ["railway_arrival","urbanisation"],0.75,0.88,["East Indian Railway"],["Howrah","Hooghly"],[]),
 (1905,None,"exact","movement","The Partition of Bengal and the Swadeshi movement",
  "Curzon's partition of Bengal along communal lines triggered the Swadeshi agitation — boycott of British goods and a revival of indigenous manufacture. The partition was annulled in 1911; the politics it created were not.",
  ["partition","agitation","craft_flourish"],0.9,0.93,["Lord Curzon","Rabindranath Tagore"],["Bengal"],[]),
 (1911,None,"exact","legislature","The capital moves from Calcutta to Delhi",
  "Annulling the partition, the Raj also removed the capital to Delhi. Calcutta kept its port and its industry but lost the administrative gravity that had concentrated investment there for 150 years.",
  ["capital_designation","regional_imbalance","revenue_decline"],0.85,0.93,["George V","Lord Hardinge"],["Calcutta","Delhi"],[]),
 (1943,1944,"exact","disaster","The Bengal Famine",
  "Wartime procurement, the denial policy on boats and rice, halted Burmese imports and refusal to divert shipping produced a famine that killed some three million. Aggregate food availability was not the binding constraint.",
  ["famine","population_loss","migration"],1.0,0.95,["Government of Bengal","War Cabinet"],["Bengal"],["contested_history"]),
 (1947,None,"exact","war","Partition and the making of West Bengal",
  "Bengal was divided; West Bengal joined India. Millions crossed in both directions over the following decade, and Calcutta absorbed a refugee influx that reshaped its politics, housing and labour market for a generation.",
  ["partition","migration","population_loss"],1.0,0.97,[],["Bengal"],[]),
 (1967,None,"exact","movement","The Naxalbari uprising",
  "A peasant revolt in Naxalbari over land seizure launched a Maoist insurgency that took its name from the village and spread far beyond Bengal, most durably into the mineral belt to the west.",
  ["rebellion","insurgency","agitation"],0.85,0.92,["Charu Majumdar","Kanu Sanyal"],["Naxalbari"],[]),
 (1978,1982,"exact","legislature","Operation Barga",
  "The Left Front registered sharecroppers, securing their tenancy and crop share. Registration rather than redistribution — it raised agricultural yields markedly without breaking landholding as Kerala had.",
  ["land_reform","agri_yield_rise"],0.85,0.88,["Left Front","Benoy Choudhury"],["West Bengal"],[]),
 (1980,2000,"decade","development","The jute economy declines",
  "Partition had left the mills in West Bengal and most of the growing land in the east; synthetics then eroded demand. Industrial Bengal's signature sector contracted through the closing decades of the century.",
  ["deindustrialisation","revenue_decline"],0.8,0.8,[],["Hooghly industrial belt"],[]),
 (2006,2008,"exact","movement","Singur and Nandigram",
  "Land acquisition for a Tata small-car plant and a chemical SEZ met sustained resistance. The projects were abandoned and the agitation broke the Left Front's rural base after three decades in power.",
  ["displacement","agitation","sez_designation"],0.9,0.9,["Tata Motors","Mamata Banerjee","Left Front"],["Singur","Nandigram"],["contested_history"]),
 (2011,None,"exact","highlight","The Left Front's 34-year government ends",
  "Trinamool Congress won power, ending the world's longest continuously elected communist government. The land politics of Operation Barga and of Singur bracket its rise and its fall.",
  ["agitation"],0.8,0.95,["Mamata Banerjee","Left Front"],["West Bengal"],[]),
]

GUJARAT = [
 (-2400,-1900,"quarter_century","development","Lothal's dock and the Harappan sea trade",
  "Lothal's brick basin — read by most excavators as a tidal dock — and Dholavira's water engineering mark Gujarat as India's earliest maritime and hydraulic economy. Bead workshops indicate export craft, not just subsistence.",
  ["port_established","craft_flourish"],0.7,0.62,["Harappan civilisation"],["Lothal","Dholavira"],["contested_history"]),
 (1026,None,"exact","war","Mahmud of Ghazni sacks Somnath",
  "The raid on the Somnath temple carried off its wealth and became one of the most contested memories in Indian history — invoked and reinterpreted continuously for the next thousand years.",
  ["invasion"],0.8,0.9,["Mahmud of Ghazni"],["Somnath"],["contested_history","sensitive"]),
 (1297,None,"exact","war","Alauddin Khalji annexes Gujarat",
  "Khalji forces defeated Karna of the Vaghela dynasty, ending Rajput rule and bringing Gujarat's ports and their customs revenue into the Delhi Sultanate.",
  ["annexation","invasion","revenue_extraction"],0.75,0.88,["Alauddin Khalji","Karna Vaghela"],["Anhilwad Patan"],[]),
 (1411,None,"exact","development","Ahmad Shah I founds Ahmedabad",
  "The new capital on the Sabarmati drew weavers, dyers and merchants. Ahmedabad's textile identity — and its guild (mahajan) form of self-organisation — dates from this foundation.",
  ["urbanisation","guild_formation","craft_flourish"],0.8,0.88,["Ahmad Shah I"],["Ahmedabad"],[]),
 (1572,1700,"decade","development","Surat as the Mughal empire's premier port",
  "Surat handled the Hajj traffic and the western trade, with Gujarati, Armenian and European merchants operating side by side. Gujarati textiles reached East Africa, the Gulf and Southeast Asia.",
  ["port_established","craft_flourish","revenue_surge"],0.9,0.85,["Mughal Empire","Gujarati merchant houses"],["Surat"],[]),
 (1614,None,"exact","legislature","The English factory at Surat",
  "After Swally, the English secured a firman for a factory at Surat — their first durable Indian foothold, and the commercial bridgehead that Bombay would later inherit.",
  ["trade_treaty","port_established"],0.7,0.88,["East India Company","Jahangir"],["Surat"],[]),
 (1668,1750,"decade","development","Bombay rises and Surat declines",
  "The cession of Bombay to the English and its fortified deep-water harbour drew trade off Surat, whose silting river and Maratha raids compounded the shift. Gujarat's mercantile capital migrated south.",
  ["port_established","revenue_decline","migration"],0.75,0.78,["East India Company"],["Surat","Bombay"],[]),
 (1861,None,"exact","development","Ahmedabad's first cotton mill",
  "Ranchhodlal Chhotalal opened the Shahpur mill, founding an Indian-owned mechanised textile industry financed by Gujarati merchant capital. Ahmedabad became the 'Manchester of the East'.",
  ["industrial_boom","craft_flourish"],0.85,0.85,["Ranchhodlal Chhotalal"],["Ahmedabad"],[]),
 (1918,None,"exact","movement","The Ahmedabad mill strike",
  "Gandhi's fast in support of mill workers produced a negotiated settlement and, from it, the Textile Labour Association — a distinctive arbitration-based union tradition rather than a confrontational one.",
  ["agitation","guild_formation"],0.7,0.88,["Mahatma Gandhi","Anasuya Sarabhai"],["Ahmedabad"],[]),
 (1930,None,"exact","movement","The Dandi March",
  "Gandhi walked 385 km from Sabarmati to Dandi to make salt in defiance of the salt monopoly, igniting nationwide civil disobedience. The march made Gujarat the stage of the freedom movement's most legible act.",
  ["agitation"],0.95,0.97,["Mahatma Gandhi"],["Sabarmati","Dandi"],[]),
 (1946,None,"exact","development","The Kaira district milk cooperative is founded",
  "Farmers in Kheda organised to bypass a monopsony milk contractor. The union — later Amul — became the model for producer-owned processing and marketing across India.",
  ["cooperative_formation"],0.85,0.9,["Tribhuvandas Patel","Verghese Kurien"],["Anand","Kheda"],[]),
 (1956,1960,"exact","movement","The Mahagujarat Movement",
  "Agitation for a separate Gujarati-speaking state out of bilingual Bombay State ran alongside the Samyukta Maharashtra movement. Both succeeded simultaneously.",
  ["language_movement","statehood_demand","agitation"],0.85,0.88,["Indulal Yagnik"],["Ahmedabad"],[]),
 (1960,None,"exact","legislature","Gujarat is formed",
  "Bombay State was divided on 1 May 1960 into Gujarat and Maharashtra, completing the linguistic reorganisation begun in 1956.",
  ["state_reorganisation","language_movement"],0.95,0.96,[],["Gujarat"],[]),
 (1970,1996,"decade","development","Operation Flood",
  "The Anand cooperative model was scaled nationally from Gujarat, making India the world's largest milk producer. A state's institutional invention became national policy.",
  ["cooperative_formation","agri_yield_rise"],0.9,0.9,["Verghese Kurien","National Dairy Development Board"],["Anand"],[]),
 (1979,None,"exact","disaster","The Machchhu dam failure at Morbi",
  "The Machchhu-II dam failed during extreme rainfall, inundating Morbi. It remains among the deadliest dam disasters recorded anywhere.",
  ["dam_built","flood","population_loss"],0.8,0.88,[],["Morbi"],[]),
 (2001,None,"exact","disaster","The Bhuj earthquake",
  "A magnitude ~7.7 earthquake devastated Kutch. The reconstruction that followed became a template for disaster-resilient rebuilding and a major channel of state capacity-building.",
  ["earthquake","population_loss","urbanisation"],0.9,0.95,[],["Bhuj","Kutch"],[]),
 (2002,None,"exact","war","The 2002 Gujarat violence",
  "Communal violence following the Godhra train burning killed over a thousand people, predominantly Muslim, and displaced many more. Accounts of state conduct remain the subject of unresolved public and legal contestation.",
  ["rebellion","migration","population_loss"],0.9,0.85,[],["Gujarat"],["contested_history","sensitive"]),
 (2003,2014,"decade","development","Vibrant Gujarat and the investment turn",
  "A biennial investor summit, land banks and single-window clearance drove chemicals, petrochemicals and autos. Growth was industry- and capital-led, with human-development indicators lagging the growth rate.",
  ["industrial_boom","sez_designation","policy_liberalisation"],0.85,0.85,["Government of Gujarat"],["Gujarat"],[]),
]
