/**
 * build-lenses.mjs — the record the knowledge sheets read.
 *
 * The atlas's data packs (atlas-data/*.js) are ~1.5 MB of researched dossiers,
 * written for a page that loads them one tab at a time from a sibling data
 * directory. The game is one self-contained HTML file, so it cannot carry
 * them whole and must not try.
 *
 * What a sheet on the table actually needs is small: one number to paint the
 * state by, and a handful of lines for the slip you open when you tap it. So
 * this reduces each pack to exactly that, state by state, and writes
 * data/game/lenses.json — tens of kilobytes instead of megabytes.
 *
 * The extraction follows tools/build-deck.mjs: each pack is a plain
 * `window.INDIA_DATA.<key> = {...};` assignment, parsed as JSON.
 *
 *   node tools/build-lenses.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

function pack(name) {
  const src = readFileSync(join(ROOT, 'atlas-data', `${name}.js`), 'utf8');
  return JSON.parse(src.match(/window\.INDIA_DATA\.\w+\s*=\s*([\s\S]*?);\s*$/)[1]);
}

const clip = (s, n) => {
  if (!s) return null;
  const t = String(s).replace(/\s+/g, ' ').trim();
  if (t.length <= n) return t;
  // Cut at a sentence end where there is one nearby, so the slip reads whole.
  const cut = t.slice(0, n);
  const stop = cut.lastIndexOf('. ');
  return (stop > n * 0.55 ? cut.slice(0, stop + 1) : `${cut.trimEnd()}…`);
};
const take = (a, n, f) => (Array.isArray(a) ? a.slice(0, n).map(f).filter(Boolean) : []);

const history = pack('history');
const heritage = pack('heritage');
const governance = pack('governance');

/* The Chronicle: what this ground remembers — events, dynasties, monuments. */
const chronicle = {};
for (const [slug, e] of Object.entries(history.states)) {
  const h = heritage.states[slug] ?? {};
  chronicle[slug] = {
    name: e.name,
    // The number the sheet paints by. Not the event count: the packs cap it,
    // so every state comes out the same shade. World-heritage weight varies
    // for a real reason — what this ground built that the world still keeps.
    n: h.unescoCount ?? 0,
    confidence: e.confidence ?? 'medium',
    summary: clip(e.summary, 260),
    dynasties: take(e.dynasties, 3, (d) => clip(d, 70)),
    first: e.keyEvents?.[0] ? { year: clip(e.keyEvents[0].year, 40), what: clip(e.keyEvents[0].event, 170) } : null,
    events: e.keyEvents?.length ?? 0,
    unesco: h.unescoCount ?? 0,
    sites: take(h.sites, 3, (s) => clip(s.name, 70)),
  };
}

/* The Order: how this ground is governed — when it was made, and by whom. */
const order = {};
for (const [slug, e] of Object.entries(governance.states)) {
  order[slug] = {
    name: e.name,
    // The number the sheet paints by: how finely this ground is administered.
    n: Number(e.districts) || 0,
    confidence: e.confidence ?? 'medium',
    summary: clip(e.summary, 260),
    capital: clip(e.capital, 90),
    formed: clip(e.formation?.date, 60),
    legislature: clip(e.legislature?.type ?? e.legislature, 90),
    policy: e.flagshipPolicies?.[0]
      ? { name: clip(e.flagshipPolicies[0].name, 80), area: clip(e.flagshipPolicies[0].area, 60) } : null,
  };
}

const out = {
  note: 'Per-state extracts for the game\'s knowledge sheets. Generated by tools/build-lenses.mjs '
      + 'from atlas-data/{history,heritage,governance}.js — see those packs and their sources '
      + 'for the full researched record.',
  sources: ['atlas-data/history.js', 'atlas-data/heritage.js', 'atlas-data/governance.js'],
  chronicle,
  order,
};

mkdirSync(join(ROOT, 'data/game'), { recursive: true });
const path = join(ROOT, 'data/game/lenses.json');
writeFileSync(path, `${JSON.stringify(out, null, 1)}\n`);

const kb = (Buffer.byteLength(JSON.stringify(out)) / 1024).toFixed(1);
console.log(`  ✓ data/game/lenses.json  ${Object.keys(chronicle).length} states × 2 sheets  ${kb} KB`);
